export const ScreenNames = {
  SplashScreen: "SplashScreen",

  SignInScreen: "SignInScreen",
  SignUpScreen: "SignUpScreen",
  MainAttendanceScreen: "MainAttendanceScreen",
  FiltersAttendanceScreen: "FiltersAttendanceScreen",
  MainTeamAttendanceScreen: "MainTeamAttendanceScreen",
  FiltersTeamAttendanceScreen: "FiltersTeamAttendanceScreen",
  TransactionsScreen: "TransactionsScreen",
  FinanceScreen: "FinanceScreen",
  ReportScreen: "ReportScreen",
  NewsScreen: "NewsScreen",
  NewsOpen: "NewsOpen",
  Settings: "Settings",
  CreateFinanceScreen:"CreateFinanceScreen",
  CreateAttendanceScreen: "CreateAttendanceScreen",
  ViewAttendanceScreen: "ViewAttendanceScreen",
  EditAttendanceScreen: "EditAttendanceScreen",
  ViewFinanceScreen: "ViewFinanceScreen",

  DrawerNavigator: "DrawerNavigator",
  DashboardScreen: "DashboardScreen",
  NotificationScreen: "NotificationScreen",
  ChangePasswordScreen: "ChangePasswordScreen",
  PolicyScreen: "PolicyScreen",
  DeleteUser:"DeleteUser",
  ContactUsScreen: "ContactUsScreen",
  LogoutScreen: "LogoutScreen",
};
