export const ScreenNames = {
  SplashScreen: 'SplashScreen',

  SignInScreen: 'SignInScreen',
  SignUpScreen: 'SignUpScreen',
  MainAttendanceScreen: 'MainAttendanceScreen',
  MainTeamAttendanceScreen: 'MainTeamAttendanceScreen',
  FiltersTeamAttendanceScreen: 'FiltersTeamAttendanceScreen',
  TransactionsScreen: 'TransactionsScreen',
  FinanceScreen: 'FinanceScreen',
  ReportScreen: 'ReportScreen',
  NewsScreen: 'NewsScreen',
  NewsOpen: 'NewsOpen',
  Settings: 'Settings',
  CreateAttendanceScreen: 'CreateAttendanceScreen',
  ViewAttendanceScreen: 'ViewAttendanceScreen',
  EditAttendanceScreen: 'EditAttendanceScreen',
  ViewFinanceScreen: 'ViewFinanceScreen',

  DrawerNavigator: 'DrawerNavigator',
  DashboardScreen: 'DashboardScreen',
  NotificationScreen: 'NotificationScreen',
  ChangePasswordScreen: 'ChangePasswordScreen',
  PolicyScreen: 'PolicyScreen',
  ContactUsScreen: 'ContactUsScreen',
  LogoutScreen: 'LogoutScreen',
};
